extern const GeoLayout wmotr_area_1_geo[];
extern const GeoLayout wmotr_area_1[];
extern const Collision wmotr_area_1_collision[];
extern const MacroObject wmotr_area_1_macro_objs[];
extern u8 wmotr_dl_Desk3_rgba16[];
extern u8 wmotr_dl_Desk_rgba16[];
extern u8 wmotr_dl_couch_rgba16[];
extern u8 wmotr_dl_hammer_shine_rgba32_ia8[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_0[20];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_1[4];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_2[8];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_3[92];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_4[12];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_4[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_5[579];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_5[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_6[37];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_6[];
extern Vtx wmotr_dl_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx wmotr_dl_Cube_mesh_layer_5_vtx_0[53];
extern Gfx wmotr_dl_Cube_mesh_layer_5_tri_0[];
extern Gfx mat_wmotr_dl_sm64_material_001[];
extern Gfx mat_revert_wmotr_dl_sm64_material_001[];
extern Gfx mat_wmotr_dl_f3dlite_material_004[];
extern Gfx mat_revert_wmotr_dl_f3dlite_material_004[];
extern Gfx mat_wmotr_dl_f3dlite_material[];
extern Gfx mat_revert_wmotr_dl_f3dlite_material[];
extern Gfx mat_wmotr_dl_f3dlite_material_003[];
extern Gfx mat_revert_wmotr_dl_f3dlite_material_003[];
extern Gfx mat_wmotr_dl_Desk_top[];
extern Gfx mat_revert_wmotr_dl_Desk_top[];
extern Gfx mat_wmotr_dl_f3dlite_material_008[];
extern Gfx mat_revert_wmotr_dl_f3dlite_material_008[];
extern Gfx mat_wmotr_dl_f3dlite_material_001[];
extern Gfx mat_revert_wmotr_dl_f3dlite_material_001[];
extern Gfx mat_wmotr_dl_f3dlite_material_002[];
extern Gfx mat_revert_wmotr_dl_f3dlite_material_002[];
extern Gfx wmotr_dl_Cube_mesh_layer_1[];
extern Gfx wmotr_dl_Cube_mesh_layer_5[];
