extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_Desk3_rgba16[];
extern u8 bob_dl_Desk_rgba16[];
extern u8 bob_dl_couch_rgba16[];
extern u8 bob_dl_hammer_shine_rgba32_ia8[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[8];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_2[92];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_3[12];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_4[579];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_5[37];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_5[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_0[56];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_f3dlite_material_004[];
extern Gfx mat_revert_bob_dl_f3dlite_material_004[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_revert_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_f3dlite_material_003[];
extern Gfx mat_revert_bob_dl_f3dlite_material_003[];
extern Gfx mat_bob_dl_Desk_top[];
extern Gfx mat_revert_bob_dl_Desk_top[];
extern Gfx mat_bob_dl_f3dlite_material_008[];
extern Gfx mat_revert_bob_dl_f3dlite_material_008[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx mat_revert_bob_dl_f3dlite_material_002[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_5[];
