#include "src/game/envfx_snow.h"

const GeoLayout mario_npc_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_npc_switch_option_left_hand_open_left_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_npc_switch_option_right_hand_open_right_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_right_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_npc_switch_option_right_hand_peace_right_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_right_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_npc_switch_option_right_hand_cap_right_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_right_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, mario_npc_switch_option_right_hand_wing_cap_right_hand_wing_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, mario_npc_switch_option_right_hand_wing_cap_right_hand_wing_cap_wings_dl_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_002_switch_opt0_eye_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_head_dl_mesh_layer_1_mat_override_eye_half_closed_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_002_switch_opt0_eye_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_head_dl_mesh_layer_1_mat_override_eye_closed_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_002_switch_opt0_eye_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_head_dl_mesh_layer_1_mat_override_eye_weak__look_left__2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_002_switch_opt0_eye_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_head_dl_mesh_layer_1_mat_override_eye_hurt__look_right__3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_002_switch_opt0_eye_switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_head_dl_mesh_layer_1_mat_override_eye_up_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_002_switch_opt0_eye_switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_head_dl_mesh_layer_1_mat_override_eye_down_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_002_switch_opt0_eye_switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_head_dl_mesh_layer_1_mat_override_eye_x_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_npc_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_npc_pelvis_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_chest_skinned_mesh_layer_1),
								GEO_ASM(0, geo_move_mario_part_from_parent),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_npc_chest_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_head_rotation),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_head_dl_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_npc_002_switch_opt0_eye_switch_opt1),
												GEO_BRANCH(1, mario_npc_002_switch_opt0_eye_switch_opt2),
												GEO_BRANCH(1, mario_npc_002_switch_opt0_eye_switch_opt3),
												GEO_BRANCH(1, mario_npc_002_switch_opt0_eye_switch_opt4),
												GEO_BRANCH(1, mario_npc_002_switch_opt0_eye_switch_opt5),
												GEO_BRANCH(1, mario_npc_002_switch_opt0_eye_switch_opt6),
												GEO_BRANCH(1, mario_npc_002_switch_opt0_eye_switch_opt7),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_upper_arm_L_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, 79, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_npc_upper_arm_L_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_lower_arm_L_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_npc_lower_arm_L_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(1, geo_switch_mario_hand),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(1, geo_mario_hand_foot_scaler),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_hand_dl_L_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, mario_npc_left_hand_open_armature),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_upper_arm_R_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -10, -79, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_npc_upper_arm_R_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_lower_arm_R_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, mario_npc_lower_arm_R_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(0, geo_switch_mario_hand),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_hand_dl_R_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, mario_npc_right_hand_open_armature),
														GEO_BRANCH(1, mario_npc_right_hand_peace_armature),
														GEO_BRANCH(1, mario_npc_right_hand_cap_armature),
														GEO_BRANCH(1, mario_npc_right_hand_wing_cap_armature),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_upper_leg_L_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_npc_upper_leg_L_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_lower_leg_L_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_npc_lower_leg_L_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_foot_L_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_npc_foot_L_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_upper_leg_R_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_npc_upper_leg_R_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_lower_leg_R_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_npc_lower_leg_R_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_foot_dl_R_skinned_mesh_layer_1),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_npc_foot_dl_R_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
